name: Chatify

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Frontend to Vercel
        run: |
          cd frontend
          vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build the project
        run: |
          cd backend
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Backend to Vercel
        run: |
          cd backend
          vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
